name: Testing Workflow

on:
  push:
    branches: [feature/create-workflow]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install
        working-directory: ./retro-board-ui

      - name: deploy gh-pages
        uses: ./retro-board-ui
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          remote_url: https://github.com/appleboy/gh-pages-action.git